class Board2D
  type coord = Integer
  
  def self.read_file: (String filename) -> [Array[String], String]
  def self.call: (String filename) ?{ (Array[String]) -> instance } -> Integer
  
  attr_accessor x: coord
  attr_accessor y: coord
  attr_accessor facing: Integer
  
  def initialize: (?x: coord, ?y: coord, ?facing: Integer) -> void
  
  alias global_x x
  alias global_y y
  def row: -> coord
  def column: -> coord
  def facing!: -> (0|1|2|3)
  def password: -> Integer
  
  def move: (?Integer steps) -> void
  
  def l: () -> Integer
  def r: () -> Integer
  def call: (String instruction) -> self
end
