class ConvexBoard < Board2D
  class LandSequence
    attr_reader range: Range[Integer]
    attr_reader obstructions: Array[Integer]
    
    def initialize: (Range[Integer] range, Array[Integer] obstructions) -> void
    def self.[]:
      (*untyped array, ?is_land: _ToProc, ?is_obstruction: _ToProc) -> LandSequence
    
    def step: (Integer from, ?Integer to) -> Integer
    def step_by: (Integer from, ?Integer steps) -> Integer
  end
  
  type sequences = Array[LandSequence]
  
  attr_reader columns: sequences
  attr_reader rows: sequences
  def initialize: (
    ?rows: sequences, ?columns: sequences,
    ?x: coord, ?y: coord, ?facing: Integer
  ) -> void
  
  def self.table_to_sequences:
    (Array[Array[untyped]] table, ?is_land: _ToProc, is_obstruction: _ToProc)
    -> sequences
  def self.[]:
    (Array[Array[untyped]] table, ?is_land: _ToProc, is_obstruction: _ToProc)
    -> instance
end
