class Directory < Hash[String, Directory]
  ROOT: Directory
  
  attr_accessor parent: Directory?
  attr_reader dir_size: Integer

  def initialize: (Directory? parent) -> void
  
  def add_file: (int amount) -> void
  def dir_sizes: () -> Array[Integer]
end
