class Valve
  attr_accessor rate: Integer
  attr_reader neighbors: Array[instance]
  attr_accessor traversed: boolish
  attr_accessor open_duration: Integer?
  def initialize: (Integer rate, *instance neighbors) -> void
  
  def unvisited_neighbors: -> Array[instance]
  
  def <=>: (instance other) -> Integer?
end

VALVES: Hash[String, Valve]
INPUT_REGEXP: Regexp
