name: GitHub Pages
on:
  push: 
    branches: [main]
    paths: [lib/**]
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - uses: actions/configure-pages@v1
    
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2'
        bundler-cache: true
      env:
        BUNDLE_RUBYGEMS__PKG__GITHUB__COM: Bearer:${{ github.token }}
    
    - name: Package YARD
      run: bundle exec yard doc
    
    - uses: actions/upload-pages-artifact@v1
      with:
        path: doc
  
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - id: deploy-pages
      uses: actions/deploy-pages@v1
