name: Check Types with Steep
on:
  push:
    branches: [main]
    paths: [lib/**, sig/**]
  pull_request:
    branches: [main]
    paths: [lib/**, sig/**]
jobs:
  
  type_check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2'
        bundler-cache: true
      env:
        BUNDLE_RUBYGEMS__PKG__GITHUB__COM: Bearer:${{ github.token }}
    
    - name: Collect RBS
      run: bundle exec rbs collection install
    
    - name: Check Types with Steep
      run: bundle exec steep check
